[project]
name = "srmodel"
version = "0.1.0"
description = "Shortened SDK model targeting package"
authors = [{ name = "Dave Garrett", email = "dgarrett@synaptics.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tools.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
infer_code_gen = "srmodel.infer_code_gen:main"