/*
 * (C) Copyright 2025 Synaptics Incorporated. All rights reserved.
 *
 * This program is the proprietary software of Synaptics and/or its licensors,
 * and may only be used, duplicated, modified or distributed under the authorized
 * license from Synaptics.
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR
 * COPYRIGHT LAW IS PROHIBITED.
 */

/*********************    Autogenerated file. DO NOT EDIT *******************
 * Generated from hello_world.tflite file.
 * Date: 2025-07-28 17:05:01.493892
 ***************************************************************************/
 #include <cstdint>  #include "inference_attributes.hpp"  namespace model {  static int8_t IFM_BUF_ATTRIBUTE input_data0[1] = { -87, };  static int8_t LABELS_ATTRIBUTE output_data0[1] = { 109, };   int8_t* get_user_input_buffer(int index) {     switch (index) {         case 0:             return input_data0;         default:             return nullptr;     } }  int8_t* get_expected_output_buffer(int index) {     switch (index) {         case 0:             return output_data0;         default:             return nullptr;     } }  }  /* namespace model */ 